---
version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
